function [v_ancestor,v,p,q,P,Q,l,P1,Q1,l1] = load_node_root(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [V_ANCESTOR,V,P,Q,P,Q,L,P1,Q1,L1] = IMPORTFILE(FILENAME) Reads data
%   from text file FILENAME for the default selection.
%
%   [V_ANCESTOR,V,P,Q,P,Q,L,P1,Q1,L1] = IMPORTFILE(FILENAME, STARTROW,
%   ENDROW) Reads data from rows STARTROW through ENDROW of text file
%   FILENAME.
%
% Example:
%   [v_ancestor,v,p,q,P,Q,l,P1,Q1,l1] = importfile('estado.dat',1, 200);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2019/08/16 14:39:42

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
v_ancestor = dataArray{:, 1};
v = dataArray{:, 2};
p = dataArray{:, 3};
q = dataArray{:, 4};
P = dataArray{:, 5};
Q = dataArray{:, 6};
l = dataArray{:, 7};
P1 = dataArray{:, 8};
Q1 = dataArray{:, 9};
l1 = dataArray{:, 10};


